// packages/zero-solid/src/use-zero-online.ts
import {createSignal, onCleanup, type Accessor} from 'solid-js';
import {useZero} from './use-zero.ts';

/**
 * Tracks the online status of the current Zero instance.
 *
 * @returns An accessor — call `online()` to get a reactive `boolean`.
 * @deprecated Use {@link useZeroConnectionState} instead, which provides more detailed connection state.
 */
export function useZeroOnline(): Accessor<boolean> {
  const zero = useZero()();

  const [online, setOnline] = createSignal<boolean>(zero.online);

  const unsubscribe = zero.onOnline(setOnline);

  onCleanup(unsubscribe);

  return online;
}

// packages/zero-react/src/use-zero-online.tsx
import {useSyncExternalStore} from 'react';
import {useZero} from './zero-provider.tsx';

/**
 * Hook to subscribe to the online status of the Zero instance.
 *
 * This is useful when you want to update state based on the online status.
 *
 * @returns The online status of the Zero instance.
 *
 * @deprecated Use {@link useZeroConnectionState} instead, which provides more detailed connection state.
 */
export function useZeroOnline(): boolean {
  const zero = useZero();
  return useSyncExternalStore(
    zero.onOnline,
    () => zero.online,
    () => zero.online,
  );
}
